services:
  # Our Node.js Application
  app:
    build: .
    ports:
      - '8000:8000'
    env_file:
      - ./.env
    restart: always
    depends_on:
      - mongo
      - redis

  # MongoDB Database Service
  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  # Redis Cache Service
  redis:
    image: redis:latest
    ports:
      - '6379:6379'

volumes:
  mongo-data: